-- AlterTable
ALTER TABLE "ProjectAssignment" ADD COLUMN IF NOT EXISTS "devMonthlyRate" INTEGER;
ALTER TABLE "ProjectAssignment" ADD COLUMN IF NOT EXISTS "candidateCommissionPercent" DOUBLE PRECISION NOT NULL DEFAULT 20.0;
ALTER TABLE "ProjectAssignment" ADD COLUMN IF NOT EXISTS "vendorCutPercent" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE "ProjectAssignment" ADD COLUMN IF NOT EXISTS "workLocation" TEXT NOT NULL DEFAULT 'REMOTE';
ALTER TABLE "ProjectAssignment" ADD COLUMN IF NOT EXISTS "engagementModel" TEXT NOT NULL DEFAULT 'C2C';

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "reminderCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "lastRemindedAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "lastRemindedChannel" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "recipientEmail" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "recipientPhone" TEXT;
ALTER TABLE "Invoice" ADD COLUMN IF NOT EXISTS "invoiceType" TEXT NOT NULL DEFAULT 'STANDARD';
