-- AlterEnum
ALTER TYPE "ClientStatus" ADD VALUE IF NOT EXISTS 'UPCOMING';
ALTER TYPE "ClientStatus" ADD VALUE IF NOT EXISTS 'RESCHEDULED';
ALTER TYPE "ClientStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
