import { ArrowRight } from "@/components/icons";
import { IndustryGrid } from "@/components/industry-grid";
import { ProcessSteps } from "@/components/process-steps";
import { SectionHeading } from "@/components/section-heading";
import { Stats } from "@/components/stats";
import { TestimonialCarousel } from "@/components/testimonial-carousel";

export default function HomePage() {
  return <main id="main-content">
    <section className="hero"><div className="hero-grid" aria-hidden="true" /><div className="site-container relative grid items-center gap-14 py-32 lg:min-h-screen lg:grid-cols-2 lg:py-24"><div><p className="hero-pill"><span />Talent & Consulting Solutions</p><h1>Connecting Talent. <span>Creating Tomorrow.</span></h1><p className="hero-copy">We help ambitious companies and professionals connect with opportunity, insight, and lasting impact.</p><div className="flex flex-wrap gap-4"><a href="/contact" className="button button-primary button-large">Start a Conversation <ArrowRight /></a><a href="/industries" className="button button-outline button-large">Explore Services</a></div></div><div className="network-visual" aria-hidden="true"><svg viewBox="0 0 500 500" fill="none"><path d="m250 100 150 100-50 150-100 70-100-70-50-150 150-100Zm0 150 100-50m-100 50-100-50m100 0v-150m0 150-100 100m100-100 100 100" /><circle cx="250" cy="100" r="28" /><circle cx="100" cy="200" r="22" /><circle cx="400" cy="200" r="22" /><circle cx="250" cy="250" r="34" /><circle cx="150" cy="350" r="18" /><circle cx="350" cy="350" r="18" /><circle cx="250" cy="420" r="24" /><text x="250" y="105">IT</text><text x="100" y="205">Pharma</text><text x="400" y="205">Biotech</text><text x="250" y="256">AVX</text><text x="150" y="355">Devices</text><text x="350" y="355">Corp</text><text x="250" y="426">Talent</text></svg></div><div className="lg:col-span-2"><p className="mb-5 text-sm font-semibold uppercase tracking-[.18em] text-slate-400">Trusted by industry leaders</p><div className="flex flex-wrap gap-x-12 gap-y-4 text-sm font-semibold text-slate-300"><span>TechFlow Solutions</span><span>MedTech Innovators</span><span>NovaBio Therapeutics</span><span>GlobalPharma Inc.</span></div></div></div></section>
    <Stats />
    <section className="section"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><div className="about-panel"><div><strong>15+ Years</strong><p>of Strategic Partnership</p></div></div><div><SectionHeading eyebrow="About Avenstrix" title="The right connection changes everything."><p>We are a specialist consulting partner built around a simple belief: exceptional people deserve exceptional opportunities.</p></SectionHeading><ul className="check-list"><li>Deep sector expertise</li><li>Global reach, personal approach</li><li>Long-term partnerships</li></ul><a className="text-link" href="/about">Meet Avenstrix Consulting <ArrowRight /></a></div></div></section>
    <section className="section section-muted"><div className="site-container"><SectionHeading eyebrow="Our Industries" title="Specialized Talent for Specialized Sectors"><p>Our focused teams understand the skills, regulations, and business dynamics that shape your industry.</p></SectionHeading><div className="mt-12"><IndustryGrid /></div></div></section>
    <section className="section"><div className="site-container"><SectionHeading eyebrow="How We Work" title="A Process Built for Precision"><p>Every search is carefully tailored, transparent, and driven by the outcomes that matter to you.</p></SectionHeading><div className="mt-12"><ProcessSteps /></div></div></section>
    <section id="testimonials" className="section testimonials"><div className="site-container"><SectionHeading light eyebrow="Client Stories" title="Trusted Partnerships. Measurable Impact."><p>See why ambitious organizations choose Avenstrix for their most important hires.</p></SectionHeading><div className="mx-auto mt-12 max-w-3xl"><TestimonialCarousel /></div></div></section>
    <section className="cta"><div className="site-container flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="eyebrow eyebrow-light">Ready when you are</p><h2>Build the team that moves your business forward.</h2></div><a href="/contact" className="button button-white">Start a Conversation <ArrowRight /></a></div></section>
  </main>;
}
